# You can use this file + build.gradle to add any libraries to your project

# Gradle Docs
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
jetbrain-annotations = "26.0.2-1"

[libraries]
jetbrain-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrain-annotations" }
